version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: db

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test-task
    volumes:
      - nps_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  nps_data: {}
